image: eu.gcr.io/gitpod-core-dev/dev-environment:observability-2022-08-15
workspaceLocation: observability/observability.code-workspace
tasks:
  - name: Install pre-commit hooks & generate manifests
    command: |
      make --always-make
      pre-commit install --install-hooks
      pre-commit run --all-files &>/dev/null
vscode:
  extensions:
    - heptio.jsonnet
    - zxh404.vscode-proto3
    - golang.go
