apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: http-prober
    app.kubernetes.io/part-of: kube-prometheus
  name: http-prober
  namespace: monitoring-satellite
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: http-prober
      app.kubernetes.io/part-of: kube-prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: http-prober
        app.kubernetes.io/part-of: kube-prometheus
    spec:
      containers:
      - image: ghcr.io/arthursens/http-prober:v0.0.1
        name: http-prober
