apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: http-prober
    app.kubernetes.io/part-of: kube-prometheus
  name: http-prober
  namespace: monitoring-satellite
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: http-prober
    app.kubernetes.io/part-of: kube-prometheus
  type: ClusterIP
