alerting:
  genericSlackChannel: ""
  slackOAuthToken: ""
certmanager:
  installServiceMonitors: false
gitpod:
  installServiceMonitors: true
grafana:
  install: false
imports: {}
namespace: monitoring-satellite
prober:
  install: false
prometheus:
  remoteWrite:
  - password: password
    url: https://example.com
    username: user
  resources: {}
pyrra:
  install: false
tracing:
  install: false
  tempoBasicPassword: password
  tempoBasicUser: user
werft:
  installServiceMonitors: false
