apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alertmanager-main
  namespace: monitoring-satellite
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: alertmanager-main
subjects:
- kind: ServiceAccount
  name: alertmanager-main
  namespace: monitoring-satellite
