apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: openvsx-proxy
    app.kubernetes.io/name: gitpod
    app.kubernetes.io/part-of: kube-prometheus
  name: gitpod-openvsx-proxy
  namespace: default
spec:
  ports:
  - name: metrics
    port: 9500
  selector:
    component: openvsx-proxy
