apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: gitpod
    app.kubernetes.io/part-of: kube-prometheus
    prometheus: k8s
    role: alert-rules
  name: gitpod-monitoring-rules
  namespace: monitoring-satellite
spec:
  groups:
  - name: gitpod-login-slo-records
    rules:
    - expr: |
        sum(rate(gitpod_server_login_requests_total{status="failed"}[5m]))
        /
        sum(rate(gitpod_server_login_requests_total[5m]))
      record: gitpod_server_login_requests_total:5m_failure_ratio
    - expr: |
        sum(rate(gitpod_server_login_requests_total{status="failed"}[30m]))
        /
        sum(rate(gitpod_server_login_requests_total[30m]))
      record: gitpod_server_login_requests_total:30m_failure_ratio
    - expr: |
        sum(rate(gitpod_server_login_requests_total{status="failed"}[1h]))
        /
        sum(rate(gitpod_server_login_requests_total[1h]))
      record: gitpod_server_login_requests_total:1h_failure_ratio
    - expr: |
        sum(rate(gitpod_server_login_requests_total{status="failed"}[2h]))
        /
        sum(rate(gitpod_server_login_requests_total[2h]))
      record: gitpod_server_login_requests_total:2h_failure_ratio
    - expr: |
        sum(rate(gitpod_server_login_requests_total{status="failed"}[6h]))
        /
        sum(rate(gitpod_server_login_requests_total[6h]))
      record: gitpod_server_login_requests_total:6h_failure_ratio
    - expr: |
        sum(rate(gitpod_server_login_requests_total{status="failed"}[1d]))
        /
        sum(rate(gitpod_server_login_requests_total[1d]))
      record: gitpod_server_login_requests_total:1d_failure_ratio
    - expr: |
        sum(rate(gitpod_server_login_requests_total{status="failed"}[3d]))
        /
        sum(rate(gitpod_server_login_requests_total[3d]))
      record: gitpod_server_login_requests_total:3d_failure_ratio
    - expr: |
        sum(rate(gitpod_server_login_requests_total{status="failed"}[30d]))
        /
        sum(rate(gitpod_server_login_requests_total[30d]))
      record: gitpod_server_login_requests_total:30d_failure_ratio
    - expr: "0.95"
      record: gitpod_server_login_requests_total:slo_target
    - expr: gitpod_server_login_requests_total:monthly_availability - gitpod_server_login_requests_total:slo_target
      record: gitpod_server_login_requests_total:error_budget_remaining
    - expr: 1 - gitpod_server_login_requests_total:30d_failure_ratio
      record: gitpod_server_login_requests_total:monthly_availability
  - name: gitpod-workspacefailure-slo-records
    rules:
    - expr: |
        (
          (
            sum(rate(gitpod_ws_manager_workspace_stops_total{reason="failed",type!~"GHOST|PREBUILD"}[5m]))
            /
            sum(rate(gitpod_ws_manager_workspace_stops_total{type!~"GHOST|PREBUILD"}[5m]))
          )
        ) + (
          (
            sum(rate(grpc_server_handled_total{grpc_method="StartWorkspace",grpc_code!~"OK|ResourceExhausted"}[5m]))
            /
            sum(rate(grpc_server_handled_total{grpc_method="StartWorkspace"}[5m]))
          )
        )
      record: gitpod_workspace_failure_total:5m_failure_ratio
    - expr: |
        (
          (
            sum(rate(gitpod_ws_manager_workspace_stops_total{reason="failed",type!~"GHOST|PREBUILD"}[30m]))
            /
            sum(rate(gitpod_ws_manager_workspace_stops_total{type!~"GHOST|PREBUILD"}[30m]))
          )
        ) + (
          (
            sum(rate(grpc_server_handled_total{grpc_method="StartWorkspace",grpc_code!~"OK|ResourceExhausted"}[30m]))
            /
            sum(rate(grpc_server_handled_total{grpc_method="StartWorkspace"}[30m]))
          )
        )
      record: gitpod_workspace_failure_total:30m_failure_ratio
    - expr: |
        (
          (
            sum(rate(gitpod_ws_manager_workspace_stops_total{reason="failed",type!~"GHOST|PREBUILD"}[1h]))
            /
            sum(rate(gitpod_ws_manager_workspace_stops_total{type!~"GHOST|PREBUILD"}[1h]))
          )
        ) + (
          (
            sum(rate(grpc_server_handled_total{grpc_method="StartWorkspace",grpc_code!~"OK|ResourceExhausted"}[1h]))
            /
            sum(rate(grpc_server_handled_total{grpc_method="StartWorkspace"}[1h]))
          )
        )
      record: gitpod_workspace_failure_total:1h_failure_ratio
    - expr: |
        (
          (
            sum(rate(gitpod_ws_manager_workspace_stops_total{reason="failed",type!~"GHOST|PREBUILD"}[2h]))
            /
            sum(rate(gitpod_ws_manager_workspace_stops_total{type!~"GHOST|PREBUILD"}[2h]))
          )
        ) + (
          (
            sum(rate(grpc_server_handled_total{grpc_method="StartWorkspace",grpc_code!~"OK|ResourceExhausted"}[2h]))
            /
            sum(rate(grpc_server_handled_total{grpc_method="StartWorkspace"}[2h]))
          )
        )
      record: gitpod_workspace_failure_total:2h_failure_ratio
    - expr: |
        (
          (
            sum(rate(gitpod_ws_manager_workspace_stops_total{reason="failed",type!~"GHOST|PREBUILD"}[6h]))
            /
            sum(rate(gitpod_ws_manager_workspace_stops_total{type!~"GHOST|PREBUILD"}[6h]))
          )
        ) + (
          (
            sum(rate(grpc_server_handled_total{grpc_method="StartWorkspace",grpc_code!~"OK|ResourceExhausted"}[6h]))
            /
            sum(rate(grpc_server_handled_total{grpc_method="StartWorkspace"}[6h]))
          )
        )
      record: gitpod_workspace_failure_total:6h_failure_ratio
    - expr: |
        (
          (
            sum(rate(gitpod_ws_manager_workspace_stops_total{reason="failed",type!~"GHOST|PREBUILD"}[1d]))
            /
            sum(rate(gitpod_ws_manager_workspace_stops_total{type!~"GHOST|PREBUILD"}[1d]))
          )
        ) + (
          (
            sum(rate(grpc_server_handled_total{grpc_method="StartWorkspace",grpc_code!~"OK|ResourceExhausted"}[1d]))
            /
            sum(rate(grpc_server_handled_total{grpc_method="StartWorkspace"}[1d]))
          )
        )
      record: gitpod_workspace_failure_total:1d_failure_ratio
    - expr: |
        (
          (
            sum(rate(gitpod_ws_manager_workspace_stops_total{reason="failed",type!~"GHOST|PREBUILD"}[3d]))
            /
            sum(rate(gitpod_ws_manager_workspace_stops_total{type!~"GHOST|PREBUILD"}[3d]))
          )
        ) + (
          (
            sum(rate(grpc_server_handled_total{grpc_method="StartWorkspace",grpc_code!~"OK|ResourceExhausted"}[3d]))
            /
            sum(rate(grpc_server_handled_total{grpc_method="StartWorkspace"}[3d]))
          )
        )
      record: gitpod_workspace_failure_total:3d_failure_ratio
    - expr: |
        (
          (
            sum(rate(gitpod_ws_manager_workspace_stops_total{reason="failed",type!~"GHOST|PREBUILD"}[30d]))
            /
            sum(rate(gitpod_ws_manager_workspace_stops_total{type!~"GHOST|PREBUILD"}[30d]))
          )
        ) + (
          (
            sum(rate(grpc_server_handled_total{grpc_method="StartWorkspace",grpc_code!~"OK|ResourceExhausted"}[30d]))
            /
            sum(rate(grpc_server_handled_total{grpc_method="StartWorkspace"}[30d]))
          )
        )
      record: gitpod_workspace_failure_total:30d_failure_ratio
    - expr: "0.99"
      record: gitpod_workspace_failure_total:slo_target
    - expr: gitpod_workspace_failure_total:monthly_availability - gitpod_workspace_failure_total:slo_target
      record: gitpod_workspace_failure_total:error_budget_remaining
    - expr: 1 - gitpod_workspace_failure_total:30d_failure_ratio
      record: gitpod_workspace_failure_total:monthly_availability
  - name: gitpod-workspace-regular-not-active-records
    rules:
    - expr: |
        sum(gitpod_ws_manager_workspace_activity_total{active="false"}) / sum(gitpod_ws_manager_workspace_activity_total)
      record: gitpod_workspace_regular_not_active_percentage
  - name: gitpod-component-node-alerts
    rules:
    - alert: GitpodNodeRunningOutOfEphemeralStorage
      annotations:
        description: Node {{ $labels.node }} is reporting {{ printf "%.2f" $value
          }}% ephemeral storage left under {{ $labels.mountpoint }}.
        runbook_url: https://github.com/gitpod-io/runbooks/blob/main/runbooks/GitpodNodeRunningOutOfEphemeralStorage.md
        summary: Node almost out of ephemeral storage
      expr: |
        (
          min (
            node_filesystem_avail_bytes{mountpoint=~"/var/lib/(kubelet|containerd)"} / node_filesystem_size_bytes{mountpoint=~"/var/lib/(kubelet|containerd)"}
          ) by (node, mountpoint) * 100
        ) - 10 < 5
      for: 10m
      labels:
        severity: critical
  - name: gitpod-login-slo-alerts
    rules:
    - alert: GitpodLoginErrorBudgetBurn
      annotations:
        description: Error budget is being burn too quickly. At this rate, the whole
          monthly budget will be burnt in less than 2 days.
        runbook_url: https://github.com/gitpod-com/observability/blob/main/runbooks/GitpodLoginErrorBudgetBurn.md
        summary: Error budget is being burn too quickly.
      expr: |
        (
          gitpod_server_login_requests_total:1h_failure_ratio > (14.4 * (1 - gitpod_server_login_requests_total:slo_target))
          and
          gitpod_server_login_requests_total:5m_failure_ratio > (14.4 * (1 - gitpod_server_login_requests_total:slo_target))
        )
        or
        (
          gitpod_server_login_requests_total:6h_failure_ratio > (6 * (1 - gitpod_server_login_requests_total:slo_target))
          and
          gitpod_server_login_requests_total:30m_failure_ratio > (6 * (1 - gitpod_server_login_requests_total:slo_target))
        )
      labels:
        severity: critical
    - alert: GitpodLoginErrorBudgetBurn
      annotations:
        description: Error budget is being burn quickly. At this rate, the whole monthly
          budget will be burnt in less than 10 days.
        runbook_url: https://github.com/gitpod-com/observability/blob/main/runbooks/GitpodLoginErrorBudgetBurn.md
        summary: Error budget is being burn quickly.
      expr: |
        (
          gitpod_server_login_requests_total:1d_failure_ratio > (3 * (1 - gitpod_server_login_requests_total:slo_target))
          and
          gitpod_server_login_requests_total:2h_failure_ratio > (3 * (1 - gitpod_server_login_requests_total:slo_target))
        )
        or
        (
          gitpod_server_login_requests_total:3d_failure_ratio > (1 * (1 - gitpod_server_login_requests_total:slo_target))
          and
          gitpod_server_login_requests_total:6h_failure_ratio > (1 * (1 - gitpod_server_login_requests_total:slo_target))
        )
      labels:
        severity: warning
  - name: gitpod-component-meta-node-alerts
    rules:
    - alert: GitpodMetaNodeOOMKills
      annotations:
        description: Meta node {{ $labels.instance }} is reporting {{ printf "%.2f"
          $value }} Out Of Memory kills in the last 10 minutes.
        runbook_url: https://github.com/gitpod-io/runbooks/blob/main/runbooks/GitpodMetaNodeOOMKills.md
        summary: A meta node is reporting OOM kills.
      expr: increase(node_vmstat_oom_kill{instance=~".*meta.*"}[10m]) > 1
      labels:
        severity: warning
    - alert: GitpodMetaNodeCPUSaturation
      annotations:
        description: Meta node {{ $labels.instance }} is reporting {{ printf "%.2f"
          $value }}% CPU usage for more than 10 minutes.
        runbook_url: https://github.com/gitpod-io/runbooks/blob/main/runbooks/GitpodMetaNodeCPUSaturation.md
        summary: High CPU Saturation of a meta node.
      expr: (1 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle", instance=~".*meta.*"}[2m]))))
        * 100 > 75
      for: 10m
      labels:
        severity: warning
  - name: gitpod-component-meta-server-alerts
    rules:
    - alert: WebsocketConnectionsNotClosing
      annotations:
        runbook_url: https://github.com/gitpod-io/runbooks/blob/main/runbooks/WebsocketConnectionsNotClosing.md
        summary: Open websocket connections are not closing for the last 10 minutes
          and accumulating.
      expr: sum(server_websocket_connection_count) == 10000
      for: 10m
      labels:
        severity: critical
  - name: gitpod-component-meta-messagebus-alerts
    rules:
    - alert: GitpodMetaMessagebusTotalQueues
      annotations:
        description: messagebus {{ $labels.pod }} is reporting {{ printf "%.2f" $value
          }} queues in total.
        runbook_url: https://github.com/gitpod-io/runbooks/blob/main/runbooks/GitpodMetaMessagebusTotalQueues.md
        summary: A messagebus has too many queues in total.
      expr: sum by (instance) (rabbitmq_queues) > 10000
      for: 2m
      labels:
        severity: critical
  - name: gitpod-component-workspace-alerts
    rules:
    - alert: GitpodWorkspaceStuckOnStarting
      annotations:
        description: '{{ printf "%.2f" $value }} regular workspaces are stuck on starting
          for more than 1 hour. Current status: "{{ $labels.reason }}"'
        runbook_url: https://github.com/gitpod-io/runbooks/blob/main/runbooks/GitpodWorkspaceStuckOnStarting.md
        summary: 5 or more workspaces are stuck on starting
      expr: |
        count(
          kube_pod_container_status_waiting_reason * on(pod) group_left kube_pod_labels{component="workspace", workspace_type="regular"}
        ) by (reason) > 5
      for: 1h
      labels:
        severity: critical
    - alert: GitpodWorkspaceStuckOnStopping
      annotations:
        description: '{{ printf "%.2f" $value }} {{ $labels.workspace_type }} workspaces
          are stuck on stopping for more than 1 hour.'
        runbook_url: https://github.com/gitpod-io/runbooks/blob/main/runbooks/GitpodWorkspaceStuckOnStopping.md
        summary: 5 or more workspaces are stuck on stopping
      expr: |
        sum(
          gitpod_ws_manager_workspace_phase_total{type="REGULAR", phase="STOPPING"}
        ) without(phase) > 5
      for: 1h
      labels:
        severity: critical
    - alert: GitpodWorkspaceStatusUpdatesCeased
      annotations:
        description: meta has not seen a workspace update in the last 10 minutes despite
          starting workspaces
        runbook_url: none
        summary: meta has not seen a workspace update in the last 10 minutes despite
          starting workspaces
      expr: |
        sum(rate(gitpod_ws_manager_bridge_status_updates_total[1m])) == 0 AND sum(rate(grpc_client_handled_total{grpc_method="StartWorkspace", grpc_service="wsman.WorkspaceManager"}[1m])) != 0
      for: 10m
      labels:
        severity: warning
    - alert: GitpodWorkspaceTooManyRegularNotActive
      annotations:
        description: too many running but inactive workspaces
        runbook_url: none
        summary: too many running but inactive workspaces
      expr: |
        gitpod_workspace_regular_not_active_percentage > 0.10 AND sum(gitpod_ws_manager_workspace_activity_total) > 100
      for: 10m
      labels:
        severity: warning
  - name: gitpod-component-ws-daemon-alerts
    rules:
    - alert: GitpodWsDaemonCrashLooping
      annotations:
        description: Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container
          }}) is restarting {{ printf "%.2f" $value }} times / 10 minutes.
        runbook_url: https://github.com/gitpod-io/runbooks/blob/main/runbooks/GitpodWsDaemonCrashLooping.md
        summary: Ws-daemon is crashlooping.
      expr: |
        increase(kube_pod_container_status_restarts_total{container="ws-daemon"}[10m]) > 0
      labels:
        severity: critical
  - name: gitpod-component-ws-manager-alerts
    rules:
    - alert: GitpodWsManagerCrashLooping
      annotations:
        description: Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container
          }}) is restarting {{ printf "%.2f" $value }} times / 10 minutes.
        runbook_url: https://github.com/gitpod-io/runbooks/blob/main/runbooks/GitpodWsManagerCrashLooping.md
        summary: Ws-manager is crashlooping.
      expr: |
        increase(kube_pod_container_status_restarts_total{container="ws-manager"}[10m]) > 0
      labels:
        severity: critical
