apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: content-service
    app.kubernetes.io/name: gitpod
    app.kubernetes.io/part-of: kube-prometheus
  name: gitpod-content-service
  namespace: default
spec:
  ports:
  - name: metrics
    port: 9500
  selector:
    component: content-service
