apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: gitpod
    app.kubernetes.io/part-of: kube-prometheus
  name: gitpod-agent-smith
  namespace: monitoring-satellite
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: metrics
  jobLabel: app.kubernetes.io/component
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app.kubernetes.io/component: agent-smith
      app.kubernetes.io/name: gitpod
      app.kubernetes.io/part-of: kube-prometheus
