apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: messagebus
    app.kubernetes.io/name: gitpod
    app.kubernetes.io/part-of: kube-prometheus
  name: gitpod-messagebus
  namespace: default
spec:
  ports:
  - name: metrics
    port: 9419
  selector:
    app.kubernetes.io/name: rabbitmq
