apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana
  namespace: monitoring-satellite
rules:
- apiGroups:
  - policy
  resourceNames:
  - kube-prometheus-restricted
  resources:
  - podsecuritypolicies
  verbs:
  - use
